### ISSUE TITLE
Reduce build size

### ISSUE THREAD

**Issue by jamescallumyoung** [jamescallumyoung/gif-provider#18]
**Is your feature request related to a problem? Please describe.**
The build size will grow quite a lot if #17 is merged due to adding the `ramda` and `monet` libraries.

**Describe the solution you'd like**
Add rollup to the build step (using [@rollup/plugin-typescript](https://github.com/rollup/plugins/tree/master/packages/typescript)) to reduce the bundle size through tree-shaking and dead code elimination.

**Describe alternatives you've considered**
Webpack is another popular bundler though it's treeshaking is reportedly worse.
Snowpack is an another up-and-coming alternative.

**Additional context**
Tree-shaking may be improved (even without a bundler) by optimising imports when building ES modules.

**Comment by fernando24164** [comment]
Hi

I made a PR adding to project Rollup with ts plugin and terser to create a bundle.
Can you assign this issue to me please?

**Comment by jamescallumyoung** [comment]
I assigned the issue to you @fernando24164. Thanks for the collaberation. I saw your comments in the PR, I'll respond to them there 👍

**Comment by jamescallumyoung** [comment]
This package is not longer being maintained.
