### ISSUE TITLE
Support Gfycat

### ISSUE THREAD

**Issue by jamescallumyoung** [jamescallumyoung/gif-provider#23]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
[Gifcat](https://gfycat.com/) is one of the biggest Gif sites, and has an API available. We should support Gyfcat as a provider backend.

The solution MUST follow the patterns used elsewhere in the project. In particular, the [Strategy Pattern](https://refactoring.guru/design-patterns/strategy) ([TS example](https://refactoring.guru/design-patterns/strategy/typescript/example)) MUST be used as in the GiphyStrategy. Ideally, the Client would be implemented as a [Singleton](https://refactoring.guru/design-patterns/singleton) ([TS example](https://refactoring.guru/design-patterns/singleton/typescript/example)) too.

**Describe alternatives you've considered**
N/A

**Additional context**
From a cursory glance, their API looked more complex than Giphy and Tenor's.
An suitable NPM package may already be available for Gfycat since they are so popular.

**Comment by jamescallumyoung** [comment]
Looking at the Strategy interface and GiphyStrategy class should give a good understanding of how the various APIs are implemented and how they are decoupled from the GifProvider.

**Comment by sethetter** [comment]
Mind if I take this?

**Comment by jamescallumyoung** [comment]
Great work @sethetter. Thanks also for the speedy and clear communication. This was a pleasure to collaberate on.

As the first person to add a new Strategy since the architecture changes in #17, do you letting me know how you felt it went? Was it easy for you - as a new contributor - to understand the codebase and a=implement the new feature?
