### ISSUE TITLE
Migrate to yarn

### ISSUE THREAD

**Issue by jamescallumyoung** [jamescallumyoung/gif-provider#4]
We prefer yarn over NPM as it is more feature-rich and more popular in the JS/TS community. As a result, we want to migrate this project to use yarn.

- replace uses of `npm` with `yarn` in package.json
- replace `package-lock.json` with `yarn.lock`
- update the documentation

**Comment by saravananselvamohan** [comment]
@jamescallumyoung . Would like to work on this issue

**Comment by jamescallumyoung** [comment]
Hi @saravananselvamohan, thanks for the contribution. I approved your PR and merged it with `master`; it will be included in the next build 🎉

Thanks again for the interest, happy hacktoberfest!
