### ISSUE TITLE
Remove old GitLab config files

### ISSUE THREAD

**Issue by jamescallumyoung** [jamescallumyoung/gif-provider#8]
This project was previously hosted on GitLab and some GitLab-specific config files can still be found in the repo. These should be removed.

**Comment by saravananselvamohan** [comment]
@jamescallumyoung . Would like to work on this.  I able to see `.gitlab-ci.yml` need to removed. If I miss any please suggest

**Comment by jamescallumyoung** [comment]
Thanks for the interest @saravananselvamohan. Feel free to pick this up. I'll assign it to you. Let me know i you have any issues. 👍

**Comment by saravananselvamohan** [comment]
@jamescallumyoung . Made the changes would like to review if any other further changes required

**Comment by jamescallumyoung** [comment]
Thanks for the contribution @saravananselvamohan, I know the change was small but it is very appreciated! 

(P.S.: Happy hacktoberfest, if you're participating!)
