### ISSUE TITLE
Enable strict option in TypeScript config

### ISSUE THREAD

**Issue by jamescallumyoung** [jamescallumyoung/gif-provider#9]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
In order to improve the developer experience, the strict option in tsconfig should be set to true. The `strict` option enables all other 'strict' checks and is the recommended way to use TypeScript.

This change will require the package to be recompiled so any compile-time issues can be caught.

**Describe alternatives you've considered**
We could leave it as-is but `strict` is recomended by TS.

**Additional context**
N/A

**Comment by mariandaniel24** [comment]
I would like to work on this, if that's possible.

**Comment by shubhi23994** [comment]
Can I take this up?

**Comment by jamescallumyoung** [comment]
Hi both, thanks for the interest! I've assigned this to @mariandaniel24 since they commented first but feel free to take it up in a couple of days @shubhi23994, if it's still open.

You're both welcome to look at the other open (unassigned) issues if you're looking for things to do and if you have a feature suggestion/request I'd be happy to see it 👍 (if you're doing hacktoberfest, I'll hapily tag the issue too 😃.)

**Comment by mariandaniel24** [comment]
Hello, thank you for the assignment, I have created a pull request with the changes: #12.

As a side note, due to the hacktoberfest spam that is happening recently, repositories are now opt-in into this challenge, you'll have to add `hacktoberfest` as a topic of this repository to enable it.

**Comment by jamescallumyoung** [comment]
Thanks for the heads up re. hacktoberfest opt-in @mariandaniel24. I'll take a look at your PR shortly 👍

**Comment by jamescallumyoung** [comment]
Thanks for the contribution @mariandaniel24 🎉
